### ISSUE TITLE
Blank issueの必要性に関して

### ISSUE THREAD

**Issue by r3qu13m** [MeiServer/.github#1]
issue作成画面の下部に *Open a blank issue* のリンクがあるので不要だと思います

![cap103](https://github.com/MeiServer/.github/assets/18735217/9185ce11-51fb-4d59-882f-8e390b6c1a83)

**Comment by mei-nico25** [comment]
そこにあるのは認知しているのですが、英語の小さい文字であるため認識しづらいというのがあります。実際にmiuさんがブランクissueどうするの? になった他、私も意識しないとそこに目が行きませんし、意識しない場合は「小さい英語で何かが書かれている」程度の認識しかできません。
そうなるのであれば、他のテンプレと同列の場所に日本語を使用して並べておく方が分かりやすく使いやすいと判断し、設置しました。

**Comment by r3qu13m** [comment]
それはそれを意図しているからです. フォーマットを外れたissueを立てること自体が許容されないためです. 
そうでなければ適切なフォーマットを立てるべきです. なんでもありのゴミ箱を用意することは後々の負荷を上げるだけであって, 立てやすくなる以外のメリットはありません.

**Comment by r3qu13m** [comment]
少なくとも, blank issue templateに関して私は次のような見解を持っています

* どうしても必要な場合のために既に用意されているものを二重に用意する必要はない
* 基本的にゴミ箱を用意することは推奨されませんし, よほどのことがない限りblank templateからの開始自体が推奨されません. だから読みづらい場所にリンクがあるのです. 
* テンプレートを用意する理由は, 書き手側の負荷軽減もありますが, それ以上に読み手の負荷軽減効果も大きいです
  - 「どこに何が書かれているのか」を探さなくてよいため
  - このため, 読み手側の負荷の高いblank issueからの手書きは自然に後回しにされがちになります
    + たとえば「雑な書き方で放置されたメモが実は核の発射コードだった」というような事態を招きかねません
  - テンプレートを用意するのであれば, 特定用途にしか使えないものばかりではなく, 一定の幅をもたせたテンプレートを用意しなければならないということでもあります

**Comment by mei-nico25** [comment]
私はissueテンプレートについて、「特定場面(バグ報告等)において必要とされる情報を事前に雛形として用意しておく」ためのものと認識しています。バグ報告に必要な要素、ブロックの追加に必要な情報がそれに当たります。
それ以外は現状「その他」と認識しており、「その他」issueもまだまだ発生すると考えています。そのため、分かりやすく作れる「その他ボタン」を作成しました。

また、書き手の負荷軽減とありますが、テンプレートによっては書き手の負荷増大の場合もあると考えています。例えば新規ブロック追加の場合に、テンプレートとして用意されている項目を全て埋めるのはそれなりの負荷になります。もちろんブロック追加を行うために誰かがそれを埋める必要はありますが。
バグ報告にしろ今後追加されるテンプレートにしろ、負荷増大と認識された場合、issueを立てる事自体を躊躇する事が考えられます。それにより、アイデア、バグ、懸念事項等が表に上がってこない、上がりにくくなる事を私は懸念しています。よって、表に上がってこないくらいなら雑な書き方でもいいからどんどんissueを立てろ、という考えにより「その他ボタン」がまだ必要であると考えます。

確かにissueを立てる事に我々は慣れてはきましたが、一気にテンプレート式に置き換える、テンプレート以外を非推奨にするにはまだ早いと考えます。テンプレートを使用してissueを立てるという事をまだほとんど行っていないこと、現在用意されているテンプレートが限定的な場面でしか使えない事が理由として上げられます。
将来テンプレートが充実したタイミングで「その他ボタン」を消すのがよいと考えます。

**Comment by r3qu13m** [comment]
> もちろんブロック追加を行うために誰かがそれを埋める必要はありますが。

issueを気軽に立てる事自体に関して2つの立場があります; 気軽に立てることでアイデアを得やすくすることを推進する, そして気軽に建てられると対応する側が困る. 

私は対応する時間が実際に存在しない側として後者に立ちます. それならば立てづらくして全項目埋まるまで書き手の負荷を増大させたほうがよいです(これは裏返すと「プログラマの負荷を軽減し, 仕様策定者にその分負担してもらう」でもあります). 特に仕様策定そのものをここでやる必要はないと考えています. それこそ既存のjiraのように非プログラマ領域で活動できるものを活用することは選択肢として先に上がるべきです. 

最初に挙げた「書き手の負荷軽減」はこれらをそつなくこなせるぐらいまでちゃんと練った状態でかける人を指していました. つまり埋めることが苦痛になるような段階で建てられるissueは私にとってスコープ外です. 

> テンプレートを使用してissueを立てるという事をまだほとんど行っていないこと、現在用意されているテンプレートが限定的な場面でしか使えない事が理由として上げられます。

これは私が今ここで書くために敢えて書かなかったことなので, 問題意識に登ってもらえて嬉しく思います. そう, 今存在するテンプレートは極めて限定的であり, 使いまわしが効きません. テンプレートを用意するのであれば「特定の場合だけ使えるもの」ではなく「そのテンプレートの適用範囲がどのぐらい広いのかを適宜検討し, 少なくとも既存のissueの8割は確実にどこかのテンプレートに取り込めるようなもの」を組むことを推奨します.

**Comment by mei-nico25** [comment]
> issueを気軽に立てる事自体に関して2つの立場があります;

私は前者に立ちます。要望や追加事項、既にテンプレートがあるバグ報告ならともかく、懸念事項やちょっとした疑問点まで立てづらくするべきではないと思っています。なぜなら「とりあえず立てろ、いいから立てろ、いらなかったらcloseしてしまえばええ」と教わってきたため、その考え方が根強いためです。バグかどうか怪しいものでも一旦議題に上げるべきだと思っていますし、それは通話だろうがDiscordだろうがissueだろうが、どこにでも場所を用意すべきであると思っています。
空のテンプレートを用意したところで、issueを立てるという行為自体には一定のハードルが存在するため、ゴミが放り込まれる事はないと考えています。そしてゴミでないのであれば、それは確認して対応すべき案件です(これは必ずプログラマがissueを確認すべきという意味ではありません、私が対応する可能性も十分にあります)。

> テンプレートを用意するのであれば「特定の場合だけ使えるもの」ではなく「そのテンプレートの適用範囲がどのぐらい広いのかを適宜検討し, 少なくとも既存のissueの8割は確実にどこかのテンプレートに取り込めるようなもの」を組むことを推奨します.

これについては少なくとも現時点あるいは近日中では不可能と考えます。理由としては、そのような作業時間が無いこと、何をどのような内容で用意するのが適切なのか私には判断が難しいこと、そしてその内容でよいのかチェックする人も思い当たらないことが上げられます。
そのようなテンプレートを用意するには数ヶ月単位での時間がかかると見込みます。よって現時点では限定的なテンプレートのみでとりあえずの運用を開始し、それら以外の利便性を確保するため「空のテンプレート」は必要である、と考えます。
先にも書きましたが、テンプレートが充実した、空のテンプレートをほとんど使わなくなった、そのようなタイミングになってから「空のテンプレート」は削除すべきである、と考えます。

**Comment by r3qu13m** [comment]
概ね確認したかったことは確認できたので, 私としてはcloseで良いと考えます. 

> issueを立てるという行為自体には一定のハードルが存在するため

これはあくまで今時点での話であって, 実際には今後増加することと思います. 仕事・趣味問わず1000件クラスの未解決issueに対して稼働可能なプログラマが数人という状況をよく見てきており, その原因はマネージャ[^1]の処理能力を越えた量のバグ報告・機能追加要望です. 期間が長くなればなるほど滞留タスクの処理に関しては難しくなりますし, 各人の慣れも発生します. このため, 私としてはその「気軽ではない」という主張は近い将来無効になるものと思っています. 

> 少なくとも現時点あるいは近日中では不可能と考えます

完全に正しく, それを今すぐできるようにする必要は一切存在しないものと思います. 私がこのissueを立てた理由はこのことを確認し, 同時に把握してもらうためでした. 

[^1]: これはMeiServerというこのorganizationで言う所の各リポジトリのマネージャであり, organizationのマネージャであるめいさんのことではありません. つまり, 今の運用方針で言う所の各プロジェクトのオーナー, 管理者のことであって, 現状プログラマが同時に引き受けているものになります. 私が「プログラマの負荷」と言ったときにはこの負荷も含んでおり, つまりそこに負荷が偏らないようにしたければまず全てのプロジェクトに対してプロマネを別途設定する所から始まるわけです. <br>少なくとも各リポジトリに対して「hogefugaさんこれどうなってますか」と聞いている限りにおいて, めいさんはそのプロジェクトの管理をhogefugaさんに任せていることになり, 同時にそのマネジメントはhogefugaさんにやってもらっていることになります. めいさんのやっているものは, その言葉で言えば「プロジェクトをまとめるプロジェクト」のマネジメントであって, 各プロジェクトのマネジメントに関しては未だ我々プログラマがやっているも同然なのです.

**Comment by mei-nico25** [comment]
それでは、今後はテンプレートの拡充を目指し、将来的には空のテンプレートを削除する事を目標として、一旦closeします。
